name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest

    permissions:
     contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "848987400@qq.com"
          git config --local user.name "Meldarkbini"
          git remote set-url origin http://git.###.com/###-front-xxx.git
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
